service: notion-email-service-fe
frameworkVersion: '3'
provider:
  name: aws
  stage: dev
  region: us-west-1



custom:
  client: 
    bucketName: notion-email-service-fe-build
    distributionFolder: client/dist
    indexDocument: index.html
    errorDocument: index.html


plugins:
  - serverless-finch
  