service: notion-email-service-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  stage: dev


package:
  patterns:
    - app.py
    - lambda_handler.py
    - '!node_modules/**'
    - '!pythonLayers/**'
    - '!venv/**'
    # - '!.env'
    # - '!.env.prod'


layers:
  general:
    path: pythonLayers/general

functions:
  api:
    handler: lambda_handler.lambda_handler
    layers:
      - !Ref GeneralLambdaLayer
    events:
      - httpApi: '*'
  create-db-user:
    handler: create_db_user.lambda_handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:*
        Resource: "*"
    layers:
      - !Ref GeneralLambdaLayer
    events:
      - cognitoUserPool:
          pool: ${self:provider.stage}-user-pool
          trigger: PostAuthentication
          existing: true

custom:
  tableName: users-table

plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

  

